### ISSUE TITLE
Anti Aliasing

### ISSUE THREAD

**Issue by D-Maxwell** [Apollo199999999/LauncherX#10]
The migration to WinUI 3 as mentioned in #3 having allowed greater icon quality extraction is greatly appreciated. The last update allowed me to consider this as an actually usable launcher, which has become much more aesthetically pleasing on top of that.

To consolidate this slew of design and rendering improvements, final touches such as anti-aliasing would really help in sealing the sharp looks this app of yours has acquired as a consequence of your efforts, which i salute.

perhaps the issue does not have to do with aliasing itself, but may reside in the way in which the icons are blitted onto their containing surface ? it would seem that the transparent pixels present in the icons are getting ignored or blitted as fully opaque, unregarding to their translucence.

please also note that this occurs regardless of the chosen scale.

here is a screenshot illustrating the issue :
![image](https://github.com/user-attachments/assets/75b0265b-761b-49b7-bd06-465e72448dc7)
the compression is not to blame.

the blending just doesn't look right.

**Comment by Apollo199999999** [comment]
Hey, are you referring to some of the icons of .lnk files being rendered too small (e.g., the Mica For Everyone icon), or are you referring to the problem of some icons appearing "pixelated" due to a lack of anti-aliasing?

**Comment by D-Maxwell** [comment]
please also note that some of the apps shown in the above screenshot are exempt from the issue despite rendering "oddly" as well, as that would be because of the lack of quality from the variants baked into the original ico files ; as such, certain application shortcuts like that of IDA are not to be considered.

**Comment by Apollo199999999** [comment]
I'll see what I can do about the anti-aliasing. Meanwhile, I'll also create a separate issue for the small icons.

**Comment by Apollo199999999** [comment]
Anti-aliasing has been added, and will be released together with other fixes in v2.1.1.
Before:
![image](https://github.com/user-attachments/assets/db69b1a4-9303-434d-9a9d-800eba846f05)

After:
![image](https://github.com/user-attachments/assets/8b0ecd46-2310-4559-8265-12ad6bf36bad)

**Comment by Apollo199999999** [comment]
The small icons have also been fixed: https://github.com/Apollo199999999/LauncherX/issues/14
