### ISSUE TITLE
Directories to Scan Through

### ISSUE THREAD

**Issue by D-Maxwell** [Apollo199999999/LauncherX#11]
given how concise i have made my environment, there are only a select few folders the contents of which i would require access to through a launcher such as yours.

however, as things currently stand, i am merely given the option to manually import files and directories as shortcuts, but not to pick locations to automatically scour and virtually merge in LauncherX.

not only would such a feature truly allow this to become a well integrated part of my workflow and system as a whole, but it would also benefit others, as by default the app does not tie into any locations, although it could.
were this to ever be considered, let alone implemented, certain shell locations could be integrated by default, such as `shell:start menu\Programs\` and its global equivalent, `shell:common start menu\Programs\`.

**Comment by Apollo199999999** [comment]
Hey, I don't quite get what you want me to add here. Would you like LauncherX to automatically add items from shell locations by default, similar to how the macOS launchpad automatically has all of the user's apps already displayed?

**Comment by Apollo199999999** [comment]
Sorry, I'm confused. Couldn't you simply use the "Add a file" button to select all the contents of a folder to add them to LauncherX all at once?

**Comment by D-Maxwell** [comment]
> Sorry, I'm confused. Couldn't you simply use the "Add a file" button to select all the contents of a folder to add them to LauncherX all at once?

this would allow for exactly this, but in a dynamic way, such that any modifications to the contents of linked folders would be reflected automatically.

**Comment by Apollo199999999** [comment]
> this would allow for exactly this, but in a dynamic way, such that any modifications to the contents of linked folders would be reflected automatically.

Wouldn't this get confusing quickly? If the user adds a "linked" folder to LauncherX, along with other items, it wouldn't be clear which items belong to the "linked" folder and which do not, which may lead to the user being confused by items automatically getting added and removed from LauncherX without needing them to explicitly do so. Additionally, let's say the user adds a "linked" folder, and the contents of the folder are automatically updated in LauncherX. How, then, would the user go about "unlinking" this folder if they want to do so?

**Comment by D-Maxwell** [comment]
Additionally, let's say the user adds a "linked" folder, and the contents of the folder are automatically updated in LauncherX. How, then, would the user go about "unlinking" this folder if they want to do so?

by ensuring that a set of linked directories is saved at all times on disk, rather than simply appending their contents and forgetting about their original location, this would not be an issue, as all one ought to do is remove a location from said set, before then letting the application refresh its displayed entries to account for the change. (no need to update the whole set, simply scouring the locations unlinked as indicated in the diff and suppressing their entries should suffice)

besides, i fail to see how this could be confusing. that being said, perhaps implementing some sort of grouping method, such as translucent coloured icon backgrounds or location titles may help ?
again, i am unsure i understand how this could confuse anyone. the current implementation already sees all files being merged into a single set without mentioning their location, regardless.
this suggestion is but an extension to automatically reflect content differences in certain set locations, without requiring the user to explicitly and manually do so themselves each time.

**Comment by Apollo199999999** [comment]
Okay, I _kinda_ see what you mean. I will have to think further on the UI for this.

**Comment by Apollo199999999** [comment]
I believe I have implemented what you requested. In LauncherX v2.1.1, the user now has the option to add "Linked" folders, which will add the contents of that folder to LauncherX, then automatically reflect any changes made to the contents of that folder in LauncherX. Contents of a "linked" folder are indicated by a small icon at the bottom left.

![image](https://github.com/user-attachments/assets/2a13ca6c-c125-4482-9653-6c64a5abd4e6)

![image](https://github.com/user-attachments/assets/927280b0-516b-46ac-8645-340c21879083)
