### ISSUE TITLE
Center App Grid

### ISSUE THREAD

**Issue by D-Maxwell** [Apollo199999999/LauncherX#12]
at improper window widths, rows of apps will wrap early, which, although certainly better than wrapping late, causing z fighting and overlaying the scrollbar onto the elements or even potentially cutting them off, still "looks off", quite literally so. the apparent distance on the horizontal sides of the app grid are then uneven, unless the width is an exact multiple of the width of an element of the grid added to its gap from the next element.

my proposal is therefore to center the app grid within its container, horizontally so.

![image](https://github.com/user-attachments/assets/95513d00-7e15-42ec-bf58-683e059c5a10)

excluding the app's refusal to scale icons lacking higher resolution images --which is another issue and isn't an easy one to tackle, and which besides seems not to actually be related to a lack of high-res variants as those featured here were present--, this looks much more concise from my standpoint.

who knows, you may even eventually decide to implement features, perhaps sorting or whatnot, which would offset the app grid by using space available to its left !

for reference, this is how the above looked before i edited it.
![image](https://github.com/user-attachments/assets/72588519-f5cd-4d09-86b6-81bf4efc0414)

**Comment by Apollo199999999** [comment]
I actually prefer left-aligned app grid, but in LauncherX v2.1.1, I have added the ability to center the app grid as well:
![image](https://github.com/user-attachments/assets/1c12a2cd-22c9-4b0f-b201-51dc1ed54611)

![image](https://github.com/user-attachments/assets/9c3e369d-470f-4958-b11a-961600846960)

**Comment by D-Maxwell** [comment]
> I actually prefer left-aligned app grid, but in LauncherX v2.1.1, I have added the ability to center the app grid as well

this looks great ! that being said, the scrollbar does come off as somewhat jarring, lying right against the outer edge of the app grid.
perhaps consider aligning it to the center or to the right of the available space to its right ?

**Comment by Apollo199999999** [comment]
Yes, that has been fixed already.

**Comment by D-Maxwell** [comment]
> Yes, that has been fixed already.

i couldn't see that from the most recent screenshot. looking forward to the 2.1.1's release !
