### ISSUE TITLE
Preload Items and Update Past Initialisation

### ISSUE THREAD

**Issue by D-Maxwell** [Apollo199999999/LauncherX#13]
currently, launching the launcher --huh-- enforces a slight delay in order for it to fully load each entry.

this is fine in and of itself, as it isn't a major annoyance, far from it.

however, is such a delay truly necessary ? couldn't the assets related to the first displayed items be saved between sessions, as to immediately be displayed, before then loading the rest of the assets in order of appearance, and only after a fully realised initialisation checking the first entries for any updates to those ?

or perhaps no assets would have to be saved, instead fetching and displaying them one at a time, perhaps accompanied by a reveal animation, i.e. a fade-in of sorts ? this could end up looking even better whilst eliminating the loading screen altogether as well.

**Comment by Apollo199999999** [comment]
Unfortunately, even if assets were saved between sessions, most of the time taken during loading comes from a) reading the user's items in LauncherX from the disk, and b) adding controls to the GridView, both of which cannot be minimised. As such, there is a need for a loading screen for these things to happen.

**Comment by D-Maxwell** [comment]
> Unfortunately, even if assets were saved between sessions, most of the time taken during loading comes from a) reading the user's items in LauncherX from the disk, and b) adding controls to the GridView, both of which cannot be minimised. As such, there is a need for a loading screen for these things to happen.

as pointed out by the very end of my initial comment, as i expected the above suggestions not to be easily feasible, how about displaying entries one at a time, with a reveal animation so as to look proper and intended ?

**Comment by Apollo199999999** [comment]
Certainly possible, but I think if I display the entries one by one with a reveal animation it would take up a significant amount of time, especially if the user has many items.

**Comment by D-Maxwell** [comment]
> Certainly possible, but I think if I display the entries one by one with a reveal animation it would take up a significant amount of time, especially if the user has many items.

Would it not take as much time as the loading currently does, and even less than that to display the initial elements ? from then on, the speed at which the rest of the items load does not have to be tied to them being shown and present on the screen ; you may either only call the reveal animation once they are visible, even if they had already been loaded before scrolling, or reserve it for entries that have just been loaded.

**Comment by Apollo199999999** [comment]
> Would it not take as much time as the loading currently does, and even less than that to display the initial elements ?

It would take the same amount of time to read and load the controls from disk, yes. By default, the GridView from WinUI already has a fade in animation when you add items, but for it to show when LauncherX is loading items, an artificial delay needs to be added between the addition of every item for the animation to play.
