### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by Copeman-1** [Apollo199999999/LauncherX#2]
You should add pages so we can sort items like games / apps / folders / sites kinda like this
Each button would open a new list view to allow people to sort everything instead of having it on one page ( i would do it myself but its above my knowledge )
![Screenshot 2023-10-14 213947](https://github.com/Apollo199999999/LauncherX/assets/87365685/31119539-4579-4711-8044-8f208807eab8)

**Comment by Apollo199999999** [comment]
I might implement this if I have the time to do so.

**Comment by Apollo199999999** [comment]
Groups will be a new feature added to LauncherX v2.1.0

![image](https://github.com/user-attachments/assets/a033efbf-4103-43c7-9562-d9fc49c8c3da)

![image](https://github.com/user-attachments/assets/74467083-2e3f-43c0-8cae-0caa59a46376)

Relevant commit - https://github.com/Apollo199999999/LauncherX/commit/2d2483d3bcaf1786e657eaab13a49e13261c9fa8
