### ISSUE TITLE
Ability to Customise Shortcuts (Arrow Indicator, Icon, Name)

### ISSUE THREAD

**Issue by D-Maxwell** [Apollo199999999/LauncherX#4]
I think the title says it all.

It would be nice being able to go from this :

![image](https://github.com/Apollo199999999/LauncherX/assets/98100481/4ca13d0e-5aff-462d-a9eb-188fccab3a04)

To this (mockup) :

![image](https://github.com/Apollo199999999/LauncherX/assets/98100481/09fed3d3-edd9-4139-93e8-97f2a54ba09d)

**Comment by Apollo199999999** [comment]
This will be possible in v2.1.0.
![image](https://github.com/user-attachments/assets/1ee76c0c-35c1-46de-85cc-3411757565db)
