### ISSUE TITLE
Acrylic Support

### ISSUE THREAD

**Issue by D-Maxwell** [Apollo199999999/LauncherX#5]
hello there ;

Using this app on Windows 10 --which I understand it most likely hasn't been built for-- would certainly feel a lot more cohesive would its background not render as an opaque, tarnished grey.

This could be fixed by calling the AcrylicBrush in its place if the OS does not support Mica (which Windows 10 does not), and possibly giving the user the option to choose between those ? (well, at the very least, a hard coded fallback would be greatly appreciated)

Another option, which I believe is doomed to be impossible, would have been to embed a Mica renderer within the app itself ; although I doubt this would be that easily doable.

Hence comes what I believe to be the easiest to add ; that being, Mica for Everyone support. All that would be needed on your end (most likely) would be not to render an additional background on top of that drawn by the Windows compositor ; then third party apps like Mica for Everyone would certainly be able to handle the rest.

**Comment by Apollo199999999** [comment]
Fallback acrylic for Windows 10 has been implemented as part of migrating to WinUI 3 - https://github.com/Apollo199999999/LauncherX/commit/6d662c3a0a7fc506da1f91fb85e64991d0dc0932
