### ISSUE TITLE
Is full screen option considered?

### ISSUE THREAD

**Issue by akamienski** [Apollo199999999/LauncherX#9]
I would like to know if full screen option is considered for this app, like in [this app for example](https://github.com/jensroth-git/WinLaunch).

**Comment by Apollo199999999** [comment]
Since I'm currently in the progress of updating LauncherX, I might as well include this in v2.1.1.
![image](https://github.com/user-attachments/assets/9960c7f3-bb87-4548-aa1d-7bc37ca1917e)
